package stock.back.service.market.biz;

import java.time.LocalDate;
import java.time.LocalDateTime;

import javax.sql.DataSource;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.transaction.support.TransactionTemplate;

import stock.back.service.common.exception.StockException;

import static org.assertj.core.api.Assertions.assertThatCode;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class MarketLedgerFreezeGuardTest {

    private JdbcTemplate jdbcTemplate;
    private TransactionTemplate transactionTemplate;
    private MarketLedgerFreezeGuard guard;

    @BeforeEach
    void setUp() {
        DataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:market_ledger_freeze_guard_%d;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false"
                        .formatted(System.nanoTime()),
                "sa",
                ""
        );
        jdbcTemplate = new JdbcTemplate(dataSource);
        transactionTemplate = new TransactionTemplate(new DataSourceTransactionManager(dataSource));
        guard = new MarketLedgerFreezeGuard(jdbcTemplate);
        jdbcTemplate.execute(
                """
                create table stock_market_business_state (
                    state_id varchar(20) primary key,
                    active_business_date date not null,
                    preparing_business_date date
                )
                """
        );
        jdbcTemplate.execute(
                """
                create table stock_post_close_cycle (
                    id bigint generated by default as identity primary key,
                    business_date date not null,
                    scope_type varchar(20) not null,
                    scope_key varchar(40) not null,
                    phase varchar(60) not null,
                    status varchar(20) not null,
                    created_at timestamp not null
                )
                """
        );
        jdbcTemplate.update(
                "insert into stock_market_business_state values ('DEFAULT', ?, null)",
                LocalDate.of(2026, 7, 3)
        );
    }

    @Test
    void acquireMutationPermit_withoutFreeze_returnsLockedActiveBusinessDate() {
        LocalDate activeBusinessDate = transactionTemplate.execute(
                status -> guard.acquireMutationPermit("cash adjustment")
        );

        org.assertj.core.api.Assertions.assertThat(activeBusinessDate)
                .isEqualTo(LocalDate.of(2026, 7, 3));
    }

    @Test
    void acquireMutationPermit_closeRequested_rejectsBeforeAccountMutation() {
        insertCycle("CLOSE_REQUESTED", "RUNNING");

        assertThatThrownBy(() -> transactionTemplate.executeWithoutResult(
                status -> guard.acquireMutationPermit("cash adjustment")
        ))
                .isInstanceOf(StockException.class)
                .hasMessageContaining("ledger freeze is in progress");
    }

    @Test
    void acquireMutationPermit_ledgerFrozen_allowsNextBusinessDayMutation() {
        insertCycle("LEDGER_FROZEN", "PENDING");

        assertThatCode(() -> transactionTemplate.executeWithoutResult(
                status -> guard.acquireMutationPermit("cash adjustment")
        )).doesNotThrowAnyException();
    }

    @ParameterizedTest
    @ValueSource(strings = {
            "CLOSE_REQUESTED",
            "ORDER_ENTRY_CLOSED",
            "EXECUTION_DRAINED"
    })
    void acquireJdbcMutationPermit_closeFreezePhase_rejectsBeforeJdbcMutation(String phase) {
        insertCycle(phase, "RUNNING");

        assertThatThrownBy(() -> transactionTemplate.executeWithoutResult(
                status -> guard.acquireJdbcMutationPermit("market-role emergency suspension")
        ))
                .isInstanceOf(StockException.class)
                .hasMessageContaining("ledger freeze is in progress");
    }

    @Test
    void acquireJdbcMutationPermit_withoutFreeze_returnsLockedActiveBusinessDate() {
        LocalDate activeBusinessDate = transactionTemplate.execute(
                status -> guard.acquireJdbcMutationPermit(
                        "market-role emergency suspension"
                )
        );

        org.assertj.core.api.Assertions.assertThat(activeBusinessDate)
                .isEqualTo(LocalDate.of(2026, 7, 3));
    }

    @Test
    void acquireJdbcPreOpenMutationPermit_preparingDate_returnsPreparedBusinessDate() {
        insertCycle("LEDGER_FROZEN", "PENDING");
        jdbcTemplate.update(
                """
                update stock_market_business_state
                   set preparing_business_date = ?
                 where state_id = 'DEFAULT'
                """,
                LocalDate.of(2026, 7, 4)
        );

        LocalDate businessDate = transactionTemplate.execute(
                status -> guard.acquireJdbcPreOpenMutationPermit("live role provisioning")
        );

        org.assertj.core.api.Assertions.assertThat(businessDate)
                .isEqualTo(LocalDate.of(2026, 7, 4));
    }

    @Test
    void acquireJdbcPreOpenMutationPermit_nonSequentialPreparingDate_rejectsMutation() {
        insertCycle("LEDGER_FROZEN", "PENDING");
        jdbcTemplate.update(
                """
                update stock_market_business_state
                   set preparing_business_date = ?
                 where state_id = 'DEFAULT'
                """,
                LocalDate.of(2026, 7, 5)
        );

        assertThatThrownBy(() -> transactionTemplate.executeWithoutResult(
                status -> guard.acquireJdbcPreOpenMutationPermit("live role provisioning")
        ))
                .isInstanceOf(StockException.class)
                .hasMessageContaining("not the next active date");
    }

    private void insertCycle(String phase, String status) {
        jdbcTemplate.update(
                """
                insert into stock_post_close_cycle(
                    business_date, scope_type, scope_key, phase, status, created_at
                )
                values (?, 'FULL_MARKET', 'ALL', ?, ?, ?)
                """,
                LocalDate.of(2026, 7, 3),
                phase,
                status,
                LocalDateTime.of(2026, 7, 3, 18, 0)
        );
    }
}
