server:
  port: 20480

spring:
  config:
    activate:
      on-profile: dev
  data:
    redis:
      host: kimd0.iptime.org
      port: 26379

database:
  datasource:
    pub:
      master:
        url: jdbc:mysql://kimd0.iptime.org:23306/STOCK_SERVICE?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        configure:
          maximum-pool-size: 8
          connection-timeout: 30000
          max-lifetime: 540000
          keepalive-time: 300000
      slave1:
        url: jdbc:mysql://kimd0.iptime.org:23306/STOCK_SERVICE?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        configure:
          maximum-pool-size: 8
          connection-timeout: 30000
          max-lifetime: 540000
          keepalive-time: 300000

stock:
  batch-client:
    base-url: ${STOCK_BATCH_API_BASE_URL}
    internal-token: ${STOCK_BATCH_INTERNAL_TOKEN}
