package stock.back.service.database.entity;

public enum StockAccountCashFlowReason {
    OPENING_GRANT,
    ADMIN_DEPOSIT,
    ADMIN_WITHDRAW,
    DIVIDEND_PAYMENT,
    CAPITAL_INCREASE_SUBSCRIPTION,
    AUTO_PROFILE_RECURRING_DEPOSIT,
    AUTO_PARTICIPANT_RECURRING_DEPOSIT
}
